kind: ConfigMap
apiVersion: v1
metadata:
  name: my-grafana
  namespace: demo
data:
  grafana.ini: |-
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    jsonData = { "httpHeaderName1": "Authorization" }
    secureJsonData = { "httpHeaderValue1": "sha256~hs2wLf78O2-gHuD5Wr9d2P_BM3zcLTr8iQoxr8Z7k10" }
    [smtp]
    enabled = true
    host = email-smtp.ap-south-1.amazonaws.com:587
    user = AKIA3OJCFBJTAAEN72KK
    password = "BKZzNfPiJQC3Yz99/XoNV3fcVEsZAoeuQW5VK384oFA7"
    from_address = grafana-uat@nsdcindia.org
    from_name = Grafana
    ehlo_identity = nsdcindia.org
    startTLS_policy = OpportunisticStartTLS
    skip_verify = false
